### DISCUSSION TITLE
Reducing wasm binary size

### DISCUSSION THREAD

**Discussion by ChrisB9** [DioxusLabs/dioxus#1119] [General]
Hi,
I built a survey with dioxus-web and the wasm binary currently is at staggering 65mb...
I found this issue here: https://github.com/DioxusLabs/dioxus/issues/732 and while I havent tried it out yet, I dont think I will gain massive amount of improvements, as 30mb for a binary still feels quite large.

Has anyone more tips on how to improve binary size?
I think the first thing I could do would be to replace serde with something smaller?

---------------------------

fyi - these are my depencencies:
```toml

dioxus = "0.3"
dioxus-logger = "0.4.1"
dioxus-web = "^0.3.2"
log = "0.4.17"
reqwest = { version = "0.11.16", features = ["json", "serde_json"]}
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
once_cell = "1.10.0"
rust-i18n = "1"
dioxus-router = "0.3.0"
web-sys = { version = "0.3.61", features = ["Window", "WindowClient"]}
fluvio-wasm-timer = "0.2.5"
timer-kit = { version = "0.1.1", features = ["fluvio-wasm-timer"]}

```
