### DISCUSSION TITLE
Call for 0.4 Testing

### DISCUSSION THREAD

**Discussion by ealmloff** [DioxusLabs/dioxus#1232] [General]
The 0.4 release is coming up soon. As part of that release, there have been many improvements to Dioxus:

- Rewritten enum based router
- Reimagined documentation
- New Fullstack crate (and suspense) with server functions
- Improved VSCode extension + CLI support

Before we release 0.4, we want to leave time for community testing. If you have time, try updating dioxus to the git version from `0.3`:
```toml
dioxus = { git = "https://github.com/DioxusLabs/dioxus" }
dioxus-desktop = { git = "https://github.com/DioxusLabs/dioxus" }
# ... other renderer, router, fermi, etc
```

Let us know if anything breaks as you update your application, or if there is any areas of the new docsite (temporarily hosted [here](https://demonthos.github.io/docsite/)) that need improvement.

Areas that need testing/feedback:
- [Doc site](https://demonthos.github.io/docsite/)
- [Router](https://demonthos.github.io/docsite/learn/router/)
- [Fullstack](https://demonthos.github.io/docsite/learn/cookbook/platforms/fullstack/)
- [VSCode extension](https://github.com/DioxusLabs/dioxus/tree/master/packages/extension)
