### DISCUSSION TITLE
Why does this `Dioxus.toml` not work with hot-reload?

### DISCUSSION THREAD

**Discussion by kirawi** [DioxusLabs/dioxus#1606] [Q&A]
I have this to use with tailwindcss:
```toml
[application]
name = "gud"
default_platform = "web"
out_dir = "dist"
asset_dir = "public"

[web.app]
title = "hi"
[web.watcher]
reload_html = true
watch_path = ["src", "public"]
[web.resource]
style = ["tailwind.css"]
[web.resource.dev]
```
and it seemingly invalidates any hot-reloading. For a fraction of a second the correct text gets sent, but then it gets reverted. If I `ctrl-f5` reload then it takes longer to get reverted, but it still gets reverted. This was fixed by deleting this config, but now I can't use tailwindcss.
