### DISCUSSION TITLE
Fetching an Element and Toggling an Active class from Rust

### DISCUSSION THREAD

**Discussion by LucasErrNotFound** [DioxusLabs/dioxus#1722] [General]
**Problem**

I'm no web developer so forgive me if I said the wrong terminologies. The idea is, when the user clicks the `Sign Up` and `Sign In` button, the class `container` should be in an active state and will execute the following `css` styles:

 ```css
.form-container {
    position: absolute;
    top: 0;
    height: 100%;
    transition: all 0.6s ease-in-out; /* Animation */
}

.sign-in {
    left: 0;
    width: 50%;
    z-index: 2;
}

.container.active .sign-in {
    transform: translateX(100%);
}

.sign-up {
    left: 0;
    width: 50%;
    opacity: 0;
    z-index: 1;
}

.container.active .sign-up {
    transform: translateX(100%);
    opacity: 1;
    z-index: 5;
    animation: move 0.6s;
}

@keyframes move {
    0%, 49.99% {
        opacity: 0;
        z-index: 1;
    }

    50%, 100% {
        opacity: 1;
        z-index: 5;
    }
}

.toggle-container {
    position: absolute;
    top: 0;
    left: 50%;
    width: 50%;
    height: 100%;
    overflow: hidden;
    transition: all 0.6s ease-in-out;
    border-radius: 150px 0 0 100px;
    z-index: 1000;
}

.container.active .toggle-container {
    transform: translateX(-100%);
    border-radius: 0px 150px 100px 0;
}

.toggle {
    background-color: #512da8; /* Violet */
    height: 100%;
    background: linear-gradient(to right, #5c6bc0, #512da8);
    color: #fff; /* Make the Letter White */
    position: relative;
    left: -100%;
    height: 100%;
    width: 200%;
    transform: translateX(0);
    transition: all 0.6s ease-in-out;
}

.container.active .toggle {
    transform: translateX(50%);
}

.toggle-panel {
    position: absolute;
    width: 50%;
    height: 100%;
    display: flex;
    align-items: center;
    justify-content: center;
    flex-direction: column;
    padding: 0 30px;
    text-align: center;
    top: 0;
    transform: translateX(0);
    transition: all 0.6s ease-in-out;
}

.toggle-left {
    transform: translateX(-200%);
}

.container.active .toggle-left {
    transform: translateX(0);
}

.toggle-right {
    right: 0;
    transform: translateX(0);
}

.container.active .toggle-right {
    transform: translateX(200%);
}
 ```

 Apparently, I already saw a solution from a YouTube video to execute the styles but it is written in JavaScript and not Rust:
 ```js
const container = document.getElementById('container');
const registerBtn = document.getElementById('register');
const loginBtn = document.getElementById('login');

registerBtn.addEventListener('click', () => {
    container.classList.add("active");
});

loginBtn.addEventListener('click', () => {
    container.classList.remove("active");
});
 ```

 This is the Rust code (This is just a mock up of the Sign Up section because the original source code is too long):
 ```rust
    cx.render(rsx! {
        div {
            class: "container",
            id: "container",

            div {
                class: "form-container sign-up",
                form {
                    h1 {"Create Account"}
                    span {
                        "or use your email  for registration"
                    }
                    input {
                        "type": "text",
                        placeholder: "Name",
                    }
                    input {
                        "type": "email",
                        placeholder: "Email",
                    }
                    input {
                        "type": "password",
                        placeholder: "Password",
                    }
                    button {
                        "Sign Up"
                    }
                }
            }

            div {
                class: "toggle-container",
                        div {
                            class: "toggle-panel toggle-right",
                            h1 {"Welcome Back!"}
                            p {"Enter your personal details to use all of site features"}
                            button {
                                class: "hidden",
                                id: "register",
                                onclick: move |cx| {
                                },
                                "Sign Up"
                            }
                        }
                    }
                }
            }
 ```
 
 **Expected Behavior**

When the `Sign Up` or `Sign In` button is clicked, it should animate so that the create account section or login section should appear via animations like this:

https://github.com/DioxusLabs/dioxus/assets/132194439/4c308014-f3f4-4619-8956-d1bb83cb10a3

**Questionnaires**

- [ ] How can I convert that JavaScript code into Rust code? So that I don't have to create a JS file.
- [ ]  Since I somehow know that it's going to be in the scope of `onclick`, how can I get the element by Id and somehow add a `classList` like from that JavaScript file? (If that is even possible)
