### DISCUSSION TITLE
Web app breaks with dx button is fine using trunk

### DISCUSSION THREAD

**Discussion by onweru** [DioxusLabs/dioxus#2606] [Q&A]
I have my cargo config as 

```toml
[package]
name = "test_app"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
chrono-tz = "0.9.0"
dioxus = { git = "https://github.com/DioxusLabs/dioxus", rev = "ffa36a67c30818cd39802be656d000e5af343f77", features=["web", "router"] }
fluent-templates = "0.9.4"
getrandom = { version = "0.2.15", features = ["js"] }
hex-literal = "0.4.1"
rand = "0.8.5"
serde = "1.0.203"
unic-langid = "0.9.5"
reqwest = { git = "https://github.com/onweru/reqwest", rev = "63c142947eb1a658934491099cb8785cde1912c7", features = ["json", "cookies", "multipart"] }
web-sys = { version = "0.3.69", features = ["HtmlDocument"]}
zxcvbn = "3.0.1"
urlencoding = "2.1.3"
async-std = "1.12.0"
serde_json = "1.0.120"
lazy-regex = "3.1.0"
futures-util = "0.3.30"
```

I have been using trunk to build the application without any errors. Why trunk, because it supports sass generation off the bat. 

Been trying to test `dx` because I eventually want to use it. But I see this error in the browser.

<img width="1378" alt="SCR-20240708-odjl" src="https://github.com/DioxusLabs/dioxus/assets/16350351/8191f90f-c4a5-49dd-a018-58f3c583989c">

I'm can't quite tell where the error is being thrown from. Maybe for web_sys unwraps, or use of `r#""` strings.  I'm willing to provide further context.
