### DISCUSSION TITLE
What causes persistent failed websocket connection logs while using dx serve?

### DISCUSSION THREAD

**Discussion by onweru** [DioxusLabs/dioxus#2811] [Q&A]
I have my dioxus.toml file looking like

```toml
[application]

# App (Project) Name
name = "My App"

# The Dioxus platform to default to
default_platform = "web"

# `build` & `serve` dist path
out_dir = "dist"

# resource (public) file folder
asset_dir = "public"

[web.app]

# HTML title tag content
title = ""

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "public", "css"]
```

The app works fine but my console is flooded with dozens of these logs

```
WebSocket connection to 'ws://localhost:8080/_dioxus' failed: 
(anonymous) My App.js:952
handleError @ My App.js:349
imports.wbg.__wbg_new_6c74223c77cfabad @ My App.js:951
$web_sys::features::gen_WebSocket::WebSocket::new::h539017c1dbaa4729 @ My App_bg.wasm:0x1162204
$dioxus_web::hot_reload::make_ws::h7f945b9a6f26dcc7 @ My App_bg.wasm:0x8b9928
$dioxus_web::hot_reload::make_ws::{{closure}}::{{closure}}::h42eb53f268c80b15 @ My App_bg.wasm:0x159eaf9
$<dyn core::ops::function::FnMut<()>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h9e2e69a38ef73242 @ My App_bg.wasm:0x15f3510
__wbg_adapter_63 @ My App.js:338
real @ My App.js:243
```

<img width="526" alt="Screenshot 2024-08-09 at 12 42 07" src="https://github.com/user-attachments/assets/b63c8552-87d1-4058-bec1-731290419ca2">
