### DISCUSSION TITLE
Build failed

### DISCUSSION THREAD

**Discussion by RamanNagar** [DioxusLabs/dioxus#3260] [General]
I encountered this error while connecting to the database.
![Screenshot from 2024-11-27 14-55-08](https://github.com/user-attachments/assets/7d4d1848-3b42-4de7-9089-6ff1c7c54cd1)

**Comment by ealmloff** [comment]
Most databases cannot be compiled to WASM. Make sure your database is not being compiled when the web feature is enabled. You can check your dependencies by running `cargo tree --features web`

You likely need to make your database dependency optional and enable it only in the server feature:
```toml
database = { version = "*", optional = true }

[features]
server = ["dep:database"]
```
