### DISCUSSION TITLE
improving profiles

### DISCUSSION THREAD

**Discussion by LuckyTurtleDev** [DioxusLabs/dioxus#3458] [Ideas]
i have the issue with long rebuild times (not clean build). the most time is needed. the most time is needed by wasm-bindgen. so i tinker with the profile settingis a bit:

```toml
[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

#take above 12 s
```

```toml
[profile]

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

#take 8s
```

```toml
[profile]

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

#take 8s (most a little bit (0.2s) better than previous setting but in deviations)
```

```toml
[profile]

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

[profile.wasm-dev]
inherits = "dev"
opt-level = 2

#take 8s. wider deviations. best case is faster and worst case is slower as settings before.
```
```toml
[profile]

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

[profile.wasm-dev]
inherits = "dev"
opt-level = 2

#take 8s. slower as previous.
```

**Conclusion:**
I think the following setting are best i find. Activating max opt-level for all dependency speed up the rebuild process a lot. But it slows down the initial build massive. However since i need do to this only once i am fine with this trade.
However wasm-bindgen  still take by far the most time. Did someone has ideas to speed up this even more?
```toml
[profile]

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

[profile.wasm-dev]
inherits = "dev"
opt-level = 1
```

**test setup**
Nothing professional. i just take my current project and switch some enum values back and forward to trigger a rebuild at the cli.
I did this a view time and report the results.
A more professional testing would be better.
My project has currently some heavy dependency like Symphonia, but itself is still very small.
