### DISCUSSION TITLE
For full stack (web+server), how do you reload the page when server changes?

### DISCUSSION THREAD

**Discussion by hsnoil** [DioxusLabs/dioxus#3587] [Q&A]
For full stack (web+server), how do you reload the page when server changes?

I tried adding it in watch_path but that doesn't work, looking at verbose it isn't even tracking changes.

Only workaround I found was splitting the code up and adding it as a dependency of web, then it rebuilds the server. Is there a better/proper way to do it?

**Comment by wiseaidev** [comment]
Hello!

You should set the `watch_path` key under the `[web.watcher]` table in `Dioxus.toml`, and it should work as expected:

```toml
[web.watcher]

reload_html = true

watch_path = ["src", "assets"]
```
