### DISCUSSION TITLE
How can I use a font in my Dioxus project

### DISCUSSION THREAD

**Discussion by ifsheldon** [DioxusLabs/dioxus#4056] [Q&A] [answered]
Hi! I'm developing my website with Dioxus. I want to use a local font file. How can I use it? I know I can simply use `asset!` to include the file, but how can I reference it in the code and CSS file? Has anyone tried that before?

**Comment by ealmloff** [comment, marked as answer]
If you move your font into your asset folder (set in your `Dioxus.toml`), then dioxus will copy and serve the font into the `/assets` folder directly without mangling the name

**Reply by ifsheldon** [reply]
Thanks! So that means I can refer the fonts in CSS as usual? like

```css
@font-face {
  font-family: "Agustina Regular";
  font-style: normal;
  font-weight: normal;
  src: local("Agustina Regular"),
    url("/assets/fonts/Agustina.woff") format("woff");
}
```

> set in your Dioxus.toml

I didn't see the related setting in the documentation? Did I missing anything?
