### DISCUSSION TITLE
Using dioxus as a templating engine?

### DISCUSSION THREAD

**Discussion by FalkWoldmann** [DioxusLabs/dioxus#4178] [Q&A] [answered]
Hi, I'm a really big fan of using the `rsx!` macro, but I only need it to construct HTML on the server. So I tried it out with axum and came up with this:

```rust
use axum::response::Html;
use axum::{Router, routing::get};
use dioxus::prelude::*;
use dioxus::ssr::render_element;

#[tokio::main]
async fn main() {
    let app = Router::new().route("/", get(root));
    let listener = tokio::net::TcpListener::bind("0.0.0.0:3000").await.unwrap();
    axum::serve(listener, app).await.unwrap();
}

async fn root() -> Html<String> {
    let content = render_element(rsx! {
        div {
            for i in 0..5 {
                "Number: {i}"
            }
        }
    });
    println!("{}", content);
    Html(content)
}
```

```toml
[package]
name = "dioxus-templating-axum"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
dioxus = { version = "0.6.3", default-features = false, features = ["ssr", "minimal"] }
tokio = { version = "1.45.0", features = ["full"] }
```

Is this a valid approach and use case for dixous or do I miss anything important?
