### DISCUSSION TITLE
get window handle to get current monitor to get monitor resolution

### DISCUSSION THREAD

**Discussion by alexzanderr** [DioxusLabs/dioxus#714] [Q&A]
hello

my goal is to get the current monitor's resolution at runtime after the config (WindowBuilder) was setup.

i've seen that to get the current monitor (https://docs.rs/wry/latest/wry/application/window/struct.Window.html#method.current_monitor) you need to get a window handle, first.

but i dont know how to get a window handle.

i've also seen this example (https://github.com/Satellite-im/Uplink/blob/dev/src/main.rs#L181-L209) from another discussion, but that doesnt work for me. because in my case launch_with_props expects `Config` instead of a closure. i dont know why? im using, i think, the same version, 0.2.4 as 
```toml
[patch.crates-io]
dioxus = { git = "https://github.com/dioxuslabs/dioxus", rev = "1e99e35" }
dioxus-desktop = { git = "https://github.com/dioxuslabs/dioxus", rev = "1e99e35" }
dioxus-web = { git = "https://github.com/dioxuslabs/dioxus", rev = "1e99e35" }
```

any ideas? thanks.
