### ISSUE TITLE
TUI getting started fails to build

### ISSUE THREAD

**Issue by lanza** [DioxusLabs/dioxus#1017]
<img width="896" alt="image" src="https://github.com/DioxusLabs/dioxus/assets/12656790/0e4970d1-920e-49a8-a22e-718f58c236d2">

https://dioxuslabs.com/docs/0.3/guide/en/getting_started/tui.html

<img width="548" alt="image" src="https://github.com/DioxusLabs/dioxus/assets/12656790/e079423a-a216-44c9-9d0a-0d50f0deaabc">

**Comment by Demonthos** [comment]
The current TUI version requires `dioxus = "0.2"`, not `dioxus = "0.3"` like the guide sugests (see https://github.com/DioxusLabs/dioxus/issues/838). That might be the issue you are running into here?

Here is code that compiles successfully on `rust 1.69.0; Windows 11`
Cargo.toml:
```toml
[package]
name = "demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "0.2"
dioxus-tui = "0.2.2"
```

main.rs:
```rust
#![allow(non_snake_case)]
// import the prelude to get access to the `rsx!` macro and the `Scope` and `Element` types
use dioxus::prelude::*;

fn main() {
    // launch the app in the terminal
    dioxus_tui::launch(App);
}

// create a component that renders a div with the text "Hello, world!"
fn App(cx: Scope) -> Element {
    cx.render(rsx! {
        div {
            "Hello, world!"
        }
    })
}
```
