### ISSUE TITLE
use state with empty string causes error

### ISSUE THREAD

**Issue by RaphaelDarley** [DioxusLabs/dioxus#1204]
**Problem**

creating a UseState from an empty string then using that in rsx causes an error.

**Steps To Reproduce**

main.rs:
```rust
use dioxus::prelude::*;

fn main() {
    dioxus_web::launch(app);
}

fn app(cx: Scope) -> Element {
    let test_state = use_state(cx, || String::from(""));
    cx.render(rsx! {
        h1 { "Test Form" }
        p { "{test_state}" } // this line causes an error at runtime
    })
}
```

cargo.toml
```toml
[dependencies]
dioxus = { git = "https://github.com/DioxusLabs/dioxus", branch = "master" }
dioxus-web = { git = "https://github.com/DioxusLabs/dioxus", branch = "master" }
```

rustup target add wasm32-unknown-unkown 
cargo install --git https://github.com/DioxusLabs/dioxus dioxus-cli
dioxus serve

**Expected behavior**

the p tag would contain no text

**Screenshots**

![image](https://github.com/DioxusLabs/dioxus/assets/69733240/b33c84ae-5c53-45af-8517-cd2ad85c4681)

**Environment:**
 - Dioxus version: nightly (#9cef71b6b98ae071291fe8fb026436bcfa0f1776)
 - Rust version: 1.68 stable
 - OS info: windows
 - App platform: web (the error does not occur on desktop)

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later
