### ISSUE TITLE
chrono::datetime::DateTime::format causes a panic at dioxus-core-0.4.1/src/scopes.rs:440:37

### ISSUE THREAD

**Issue by vmenge** [DioxusLabs/dioxus#1357]
**Problem**

When calling `chrono::datetime::DateTime::format` while using  `dioxus-fullstack`, I get the following panic
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error', /home/vmenge/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dioxus-core-0.4.1/src/scopes.rs:440:37
thread 'tokio-runtime-worker' panicked at 'not yet implemented: generally, scopes should be sync, only if being traversed', /home/vmenge/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dioxus-ssr-0.4.0/src/renderer.rs:112:38
// a bunch more
```

**Steps To Reproduce**

Follow [Getting Started / Fullstack](https://dioxuslabs.com/learn/0.4/getting_started/fullstack) on the 0.4 learn page, then [Guide / Your First Component](https://dioxuslabs.com/learn/0.4/guide/state) to the end.

I can reproduce with just 
```rs
fn main() {
    LaunchBuilder::new(Break).launch();
}

fn Break(cx: Scope) -> Element {
    let time = Utc::now().format("%D %1:%M %p");

    render! {
        "{time}"
    }
}
```

However while this gives me an error on `scopes.rs:440`, it does not give me the one on `renderer.rs:112` as if following the guide.

My `Cargo.toml`
```toml
[dependencies]
dioxus = "*"
dioxus-fullstack = "*"
chrono = { version = "0.4.26", features = ["serde"] }
serde = "1.0.183"

[features]
default = []
ssr = ["dioxus-fullstack/axum"]
web = ["dioxus-fullstack/web"]
```

**Expected behavior**

`DateTime` should've been formatted into a string :D

**Screenshots**

![image](https://github.com/DioxusLabs/dioxus/assets/29336665/12dfbbfe-528e-4328-a377-59b05dc3d770)

**Environment:**
 - `dioxus` version: 0.4.0
 - `dioxus-fullstack` version: 0.4.1
 - Rust version: 1.71.1 (eb26296b5 2023-08-03)
 - OS info: Ubuntu 22.04.2 LTS on Windows 11 x86_64 
 - App platform: `web`/ `fullstack`

**Questionnaire**
- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later
