### ISSUE TITLE
Conditional components still taking space

### ISSUE THREAD

**Issue by marcerhans** [DioxusLabs/dioxus#1368]
**Problem**
If you have a stylesheet like this and a component as seen below:
```CSS
*:not(html, head, style, script) {
    display: flex;
    box-sizing: border-box;
    margin: 0;
    padding: 0;
    width: 100%;
    height: 100%;
    max-width: 100%;
    max-height: 100%;
    overflow: visible;
}

html,
body {
    background-color: #444444;
    width: 100vw;
    height: 100vh;
}
```
```Rust
render! {
    div {
        background_color: "green",
        flex_direction: "column",
        h1 { "High-Five counter: {count}" }
        button { onclick: move |_| count += 1, "Up high!" }
        button { onclick: move |_| count -= 1, "Down low!" }
        if *count.get() > 1 {
            render! {
                div {
                    background_color: "blue",
                    "hej"
                }
            }
        }
    }
}
```
Then the conditionally rendered component will still take up space, as seen in the screenshot further down.

**Steps To Reproduce**
See description.

**Expected behavior**
The conditionally rendered component should not take any *actual* space.

A solution I currently use is this this addition to my stylesheet:
```CSS
*[hidden] {
    display: none
}
```
This makes it so the component is not added to the view at all. Maybe this can be used as a solution, rather than having a html attribute 'hidden=""'?

**Screenshots**
![Screenshot from 2023-08-16 13-15-47](https://github.com/DioxusLabs/dioxus/assets/121002093/805d5960-7acb-451e-8ba4-64c5b10d1d42)

**Environment:**
 - Dioxus version: 0.4.0
 - Rust version: 1.71.1
 - OS info: Fedora 37
 - App platform: web
