### ISSUE TITLE
Variable interpolation does not work with tailwind classes

### ISSUE THREAD

**Issue by lostb1t** [DioxusLabs/dioxus#1432]
**Problem**

**Steps To Reproduce**

```rust
fn Test(cx: Scope) -> Element {
    let test = "should be renderered in class".to_string();
    render!{ div { 
        class: "md:bg-[('{test}')]",
        "Rerender or not" 
    } }
} 
```

produces the following tailwind css

```css
  .md\:bg-\[\(\'\{test\}\'\)\] {
    background-image: url('test');
  }
```

**Expected behavior**

Would expect the variable value to be rendered. in hindsight this is not possible because tailwind uses unprocessed jsx.

```css
  .md\:bg-\[\(\'should be renderered in class\'\)\] {
    background-image: url('should be renderered in class');
  }
```

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later
