### ISSUE TITLE
Feature parity with `tauri build`

### ISSUE THREAD

**Issue by heyrict** [DioxusLabs/dioxus#1437]
## Specific Demand

Currently, dioxus has two building systems, `dx build` and `dx bundle`. While `dx build` is a wrapper around `cargo build` with side-effects, `dx bundle` is a wrapper around `tauri_bundler::bundle::bundle_project`.

What tauri does in `tauri build` is to [Run side-effects in `tauri_build::build()`](https://github.com/tauri-apps/tauri/blob/7db1c31e479b53cd7c5a35181ca678790b6e7058/tooling/cli/templates/app/src-tauri/build.rs), [check the config](https://github.com/tauri-apps/tauri/blob/7db1c31e479b53cd7c5a35181ca678790b6e7058/tooling/cli/src/build.rs#L151), then [bundle_project()](https://github.com/tauri-apps/tauri/blob/7db1c31e479b53cd7c5a35181ca678790b6e7058/tooling/cli/src/build.rs#L151), and [update the build binary/installer after bundling](https://github.com/tauri-apps/tauri/blob/7db1c31e479b53cd7c5a35181ca678790b6e7058/tooling/cli/src/build.rs#L155).

Currently, both two building commands lacks the side-effects from tauri, resulting in webview not properly bundled in the windows installer (see #1321), no app signing, and potentially some mobile/Mac related issues.

## Implement Suggestion

The pre- and post-bundling side-effects should be implemented in either command, or preferrably use the same command for building (see #1387).

**Comment by improving-rigmarole** [comment]
Greetings,

I was about to make a new issue, but found this one and it seems related enough : 

Environment:
- Dioxus version: 0.4.0
- dioxus-cli version : 0.4.1  (hence [tauri_bundler 1.3.0](https://github.com/DioxusLabs/dioxus/blob/v0.4.1/packages/cli/Cargo.toml#L80))
- Rust version: 1.73.0
- OS info: Windows
- App platform: desktop

I wanted to run `dx bundle --release --package nsis`,  but dx panicked [`"nsis is not a valid package type"`](https://github.com/DioxusLabs/dioxus/blob/v0.4.1/packages/cli/src/cli/bundle.rs#L147)

and by checking the [`PackageType` enum and mapping to `tauri_bundler`](https://github.com/DioxusLabs/dioxus/blob/v0.4.1/packages/cli/src/cli/bundle.rs#L20-L61), the `PackageType::Nsis` doesn't exist in `dioxus-cli`, 
while it does exist in [`tauri_bundler 1.3.0`](https://github.com/tauri-apps/tauri/blob/tauri-bundler-v1.3.0/tooling/bundler/src/bundle/settings.rs#L22-L55).

So the only current way to get an Nsis bundle is to not specify `--package`, 
and tauri_builder gets its defaults of building all packet types for the platform (here both Msi and Nsis).

**Comment by Andrew15-5** [comment]
I assume requesting https://v2.tauri.app/distribute/windows-installer/#compiling-a-wix-installer-for-each-language-in-a-list to work would fit here nicely. Currently, NSIS bundle only uses English.

I tried adding some of this:

```toml
[bundle.windows]
# webview_install_mode = "DownloadBootstrapper"
webview_install_mode = "Skip"

[bundle.windows.nsis]
display_language_selector = true
install_mode = "CurrentUser"
# template = ""
# header_image = ""
# sidebar_image = ""
# installer_icon = ""
# install_mode: NSISInstallerMode,
# languages = []
# custom_language_files = {}
# compression = ""
# installer_hooks = ""
# minimum_webview2_version = ""

[bundle.windows.wix]
language = [["ru-RU", ""]]
fragment_paths = []
component_group_refs = []
component_refs = []
feature_group_refs = []
feature_refs = []
merge_refs = []
skip_webview_install = true
enable_elevated_update_task = false
fips_compliant = true
```

But not only I cannot specify `null` in TOML, if I omit stuff it will say that I missed some setting, while it doesn't happen if I don't configure anything at all. And the `nsis/x64` directory still only has `English.nsh`. So it reads the settings, but somehow not uses them or something.
