### ISSUE TITLE
Dioxus CLI referencing non-existant `tool` subcommand

### ISSUE THREAD

**Issue by Gobidev** [DioxusLabs/dioxus#1495]
**Problem**

I added
```toml
[application.tools]
binaryen = { wasm_opt = true }
```
to my `Dioxus.toml` which resulted in the warning:
```
[WARN] Binaryen tool not found, you can use `dx tool add binaryen` to install it.
```
However, `dx` does not have a `tool` subcommand (anymore).
The warning also appears when `binaryen` is installed on the system.

**Expected behavior**

`dx` does not reference a non-existant subcommand.
