### ISSUE TITLE
mobile_demo: `cx.needs_update_any(ScopeId::ROOT)` hangs on Android

### ISSUE THREAD

**Issue by bbigras** [DioxusLabs/dioxus#1525]
**Problem**

`cx.needs_update_any(ScopeId::ROOT)` hangs.

https://github.com/DioxusLabs/dioxus/blob/459f24d5e9ef0e03a3bbd037342c60bbde409dbf/examples/mobile_demo/src/lib.rs#L75

**Steps To Reproduce**

- cd examples/mobile_demo
- `cargo mobile init --skip-targets-install`
- `cargo android run` with Android phone plugged in

**Expected behavior**

Something to happens

**Screenshots**

**Environment:**
 - Dioxus version: `master`
 - Rust version: rustc 1.72.1 (d5c2e9c34 2023-09-13)
 - OS info: linux
 - App platform: android 14 (pixel 6 pro)

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
This seems like a duplicate of https://github.com/DioxusLabs/dioxus/issues/1158

https://github.com/DioxusLabs/dioxus/pull/1428 should fix your problem. It is breaking which is why it is not already merged. You can test that branch with:
```toml
dioxus = { git = "https://github.com/ealmloff/dioxus" branch = "bump-wry" }
dioxus-mobile = { git = "https://github.com/ealmloff/dioxus" branch = "bump-wry" }
# any other dioxus dependancies you have
```

**Comment by bbigras** [comment]
You are right, it's fine with:

```toml
dioxus = { git = "https://github.com/ealmloff/dioxus", branch = "bump-wry" }
dioxus-mobile = { git = "https://github.com/ealmloff/dioxus", branch = "bump-wry" }
dioxus-desktop = { git = "https://github.com/ealmloff/dioxus", branch = "bump-wry" }
```

Thanks!
