### ISSUE TITLE
failed to resolve: could not find `Config` in `dioxus_hot_reload` could not find `Config` in `dioxus_hot_reload`

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [DioxusLabs/dioxus#1545]
**Problem**
I am just getting started with Rust and Dioxus. I am trying to follow the "Hot reloading" steps in https://dioxuslabs.com/learn/0.4/getting_started/fullstack.
This is my file:
```rs
#![allow(non_snake_case, unused)]
use dioxus::prelude::*;
use dioxus_fullstack::prelude::*;

fn main() {
    hot_reload_init!();
    LaunchBuilder::new(app).launch();
}

fn app(cx: Scope) -> Element {
    let mut count = use_state(cx, || 0);

    cx.render(rsx! {
        h1 { "High-Five counter: {count}" }
        button { onclick: move |_| count += 1, "Up high!" }
        button { onclick: move |_| count -= 1, "Down low!" }
    })
}
```

**Steps To Reproduce**

- Follow this guide: https://dioxuslabs.com/learn/0.4/getting_started/fullstack
- Add `hot_reload_init!()` to the `main` fn

**Expected behavior**
Server should listen on port 8080 and serve the app, with hot reloading

**Screenshots**
![image](https://github.com/DioxusLabs/dioxus/assets/52586855/5de28f44-6ccb-4aeb-9df7-7f46adfed2f7)

**Environment:**
 - Dioxus version: ["0.4.0"]
 - Rust version: [1.73.0]
 - OS info: [Fedora]
 - App platform: [`web`]

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
You don't need that line anymore. Hot reloading will be enabled when you add the flag to the cli automatically. However hot reloading will only update the server code on the published version of Dioxus. To hot reload the client code as well you can use the git version of the CLI:
```
cargo install --git https://github.com/DioxusLabs/dioxus dioxus-cli
dx serve --hot-reload --platform fullstack
```

**Comment by ChocolateLoverRaj** [comment]
@ealmloff I switched to the GitHub version of the CLI. This is what happens:
```
08:00:57 rajas@redrix demo ±|master ✗|→ dx serve --hot-reload --platform fullstack
error: invalid value 'fullstack' for '--platform <PLATFORM>'
  [possible values: web, desktop]

For more information, try '--help'.
```

When I run `dx serve --hot-reload --platform web`, the page loads but it is empty (no difference for a page that should be 404 like `localhost:8080/a`)

**Comment by ChocolateLoverRaj** [comment]
I tried that just now and I get this error now:
```
04:38:42 rajas@redrix demo ±|master ✗|→ dx serve --hot-reload --platform fullstack
[WARN] You appear to be creating a Dioxus project from scratch; we will use the default config
[INFO] 🚅 Running build command...
Error: 🚫 Serving project failed: error: Only features sync,macros,io-util,rt,time are supported on wasm.
   --> /home/rajas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/lib.rs:471:1
    |
471 | compile_error!("Only features sync,macros,io-util,rt,time are supported on wasm.");
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


04:39:05 rajas@redrix demo ±|master ✗|→ error: Broken pipe (os error 32)

04:39:07 rajas@redrix demo ±|master ✗|→ error: could not compile `tokio` (lib) due to 2 previous errors
```

**Comment by ealmloff** [comment]
It looks like you have the tokio dependency enabled on the web version of your build. Tokio doesn't support WASM, so when you use fullstack you need to make the tokio dependency optional and enable it only when the `ssr` feature is enabled like this:
```toml
[dependencies]
dioxus = { version = "*" }
dioxus-fullstack = { version = "*" }
tokio = { version = "1", optional = true }

[features]
default = []
ssr = ["dioxus-fullstack/axum", "tokio"]
web = ["dioxus-fullstack/web"]
```

What does your `Cargo.toml` look like?

**Comment by ChocolateLoverRaj** [comment]
This is what my `Cargo.toml` looked like:
```toml
[package]
name = "demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "0.4.0"
dioxus-desktop = "0.4.0"
dioxus-fullstack = "0.4.1"
dioxus-web = "0.4.0"

[features]
default = []
ssr = ["dioxus-fullstack/axum"]
web = ["dioxus-fullstack/web"]
```

**Comment by ChocolateLoverRaj** [comment]
I tried using the `Cargo.toml` that u commented in https://github.com/DioxusLabs/dioxus/issues/1545#issuecomment-1765443776:
```
[package]
name = "demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "*" }
dioxus-fullstack = { version = "*" }
tokio = { version = "1", optional = true }

[features]
default = []
ssr = ["dioxus-fullstack/axum", "tokio"]
web = ["dioxus-fullstack/web"]
```
and this is the error I get now:
```
09:45:33 rajas@redrix demo ±|master ✗|→ dx serve --hot-reload --platform fullstack
[WARN] You appear to be creating a Dioxus project from scratch; we will use the default config
[INFO] 🚅 Running build command...
| ⚙️ Compiling itoa 1.0.9 (registry+https://github.com/rust-lang/crates.io-index)                                                                    [INFO] 👑 Build done.
[WARN] failed to parse `name` custom section Invalid name type (at offset 3843808)
thread 'main' panicked at /home/rajas/.cargo/git/checkouts/collect-assets-782b2f78faca8d5e/772aa45/cli-support/src/manifest.rs:47:51:
called `Result::unwrap()` on an `Err` value: Io(NotFound)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ealmloff** [comment]
> This is what my `Cargo.toml` looked like:
> 
> ```toml
> [package]
> name = "demo"
> version = "0.1.0"
> edition = "2021"
> 
> # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
> 
> [dependencies]
> dioxus = "0.4.0"
> dioxus-desktop = "0.4.0"
> dioxus-fullstack = "0.4.1"
> dioxus-web = "0.4.0"
> 
> [features]
> default = []
> ssr = ["dioxus-fullstack/axum"]
> web = ["dioxus-fullstack/web"]
> ```

Dioxus desktop will pull in tokio. You need three different features: one for desktop, one for web, and one for the server. Each feature will pull in a different render:

```toml
[dependencies]
dioxus = "0.4.0"
# dioxus fullstack needs to be optional so that it isn't active on the web or server version
dioxus-desktop = { version = "0.4.0", optinal = true }
# dioxus fullstack needs to be optional so that it isn't active on the desktop version
dioxus-fullstack = { version = "0.4.1", optional = true }
# dioxus web needs to be optional so that it isn't active on the server or desktop version
dioxus-web = { version = "0.4.0", optional = true }

[features]
default = []
ssr = ["dioxus-fullstack", "dioxus-fullstack/axum"]
web = ["dioxus-fullstack", "dioxus-fullstack/web"]
desktop = ["dioxus-desktop"]
```

**Comment by ealmloff** [comment]
> thread 'main' panicked at /home/rajas/.cargo/git/checkouts/collect-assets-782b2f78faca8d5e/772aa45/cli-support/src/manifest.rs:47:51:
called `Result::unwrap()` on an `Err` value: Io(NotFound)

It looks like the new asset support in the CLI is failing to load the lockfile in your workspace.

It currently tries to find the lockfile by running [cargo metadata](https://doc.rust-lang.org/cargo/commands/cargo-metadata.html) looking at the `workspace_root` and adding `Cargo.lock` to that path. What does your workspace and `cargo metadata` output look like?

**Comment by ChocolateLoverRaj** [comment]
For now I'm just trying to get fullstack to work, so do I need the web and desktop options for that? Here is the output of `cargo metadata`:
[cargo_metadata.json](https://github.com/DioxusLabs/dioxus/files/13030406/cargo_metadata.json)

**Comment by ealmloff** [comment]
> For now I'm just trying to get fullstack to work, so do I need the web and desktop options for that? Here is the output of `cargo metadata`: [cargo_metadata.json](https://github.com/DioxusLabs/dioxus/files/13030406/cargo_metadata.json)

If you just want fullstack you only need dioxus and dioxus-fullstack dependancies:
```toml
[dependencies]
dioxus = { version = "*" }
dioxus-fullstack = { version = "*" }

[features]
default = []
ssr = ["dioxus-fullstack/axum"]
web = ["dioxus-fullstack/web"]
```

Do you have a Cargo.lock file at `/home/**yourusername**/Documents/rust-playground/demo/Cargo.lock`?
