### ISSUE TITLE
Proposal: Deny usage of panicking code, e.g., `.unwrap()`

### ISSUE THREAD

**Issue by tigerros** [DioxusLabs/dioxus#1658]
## Specific Demand

*This shouldn't apply to examples and tests.*

This is pretty drastic, but it would improve the reliability and predictability of the framework. I'm fine if this gets rejected for now, but I do think that it should be a part of v1.0.0 (if Dioxus reaches it), which should put great emphasis on stability. Therefore, starting early would mean less refactoring in the future. I don't suggest forbidding code, but rather denying it, meaning that it would still be possible to use the offending code by adding `#[allow(...)]` to it. However, this would at least remind developers that it's not recommended and encourage them to provide a reason as to why their code is okay.

## Implement Suggestion

Add the following to the workspace `Cargo.toml` (requires Rust 1.74.0):

```toml
[workspace.lints.clippy]
panic = "deny"
unwrap_used = "deny"
expect_used = "deny"
exit = "deny"
indexing_slicing = "deny"
index_refutable_slice = "deny"
string_slice = "deny"
unchecked_duration_subtraction = "deny"
unreachable = "deny"
as_conversions = "deny"
large_futures = "deny"
large_stack_arrays = "deny"
large_stack_frames = "deny"
```

Then add the following to the `Cargo.toml` of each package (requires Rust 1.74.0):

```toml
[lints]
workspace = true
```
