### ISSUE TITLE
Index is Being Copied to style.css when index_on_404 path is executed

### ISSUE THREAD

**Issue by baxterjo** [DioxusLabs/dioxus#1779]
**Problem**

When I refresh a naively nested page that is not the index page on localhost while using `dx serve` the contents of style.css (my projects local stylesheet) are being overwritten by the contents of index.html.

One note is that this seems to only happen when naively nesting routes in the router. That is to say that it only happens when you hard code the nesting rather than using a #[nest] macro.

eg:
```rust
#[derive(Routable, Clone, PartialEq, Debug)]
#[rustfmt::skip]
pub enum Route {
    #[layout(NavBar)]
        #[route("/")]
        Home {},
        #[route("/about", About)]
        About {},
        #[route("/projects", Projects)]
        Projects{},
        #[route("/projects/alarm-clock")]
        AlarmClock {},
    #[end_layout]
    #[route("/:..route")]
    PageNotFound { route: Vec<String> },
}
```

**Steps To Reproduce**

Project Setup:
```toml
# Dioxus.toml
[application]

# App name
name = "baxterjo_webapp"

# The Dioxus platform to default to
default_platform = "web"

# `build` & `serve` output path
out_dir = "docs"

# The static resource path
asset_dir = "public"

[web.app]

# HTML title tag content
title = "Jordan Baxter"

[web.watcher]

# When watcher is triggered, regenerate the `index.html`
reload_html = true
index_on_404 = true

# Which files or dirs will be monitored
watch_path = ["src", "public", "public/css"]

# Include style or script assets
[web.resource]

# CSS style file
style = [
    "https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css",
    "https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.4.2/css/fontawesome.min.css",
    "https://fonts.googleapis.com/css?family=Montserrat:300,400,500,700",
    "css/style.css",
]

# Javascript code file
script = [
    "https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js",
]

[web.resource.dev]

# Same as [web.resource], but for development servers

# CSS style file
style = []

# JavaScript files
script = []

[[web.proxy]]
backend = "http://localhost:8000/api/"
```

- Setup a web project that has a `style.css` in the public directory. Mine is under `public/css/style.css`
- Make the include of that stylesheet the last in your list of stylesheets in `Dioxus.toml` (I'm not sure if this has an effect, but it is how mine is setup.)
- Setup a router like above
- Run `dx serve` with or without the `--hot-reload` option
- Navigate to "/projects/alarm-clock" or similar nested route
- Hit refresh
- If your style.css file has any selectors that apply to this page you should see a change
- Open page inspector and navigate to the style editor
- Scroll down to style.css, file should have the contents of index.html in it

**Expected behavior**

If using the nest macro is required for nested paths, compilation should fail on the router with a message that tells the user to use the `#[nest]` macro.

If using the nest macro is not required, then the router should route the user to the correct page with no issues.

**Screenshots**
Before Refresh (navigating to this page by clicking through app)
![image](https://github.com/DioxusLabs/dioxus/assets/73496400/df55bd05-1a7f-4da0-b044-88e6a69ceaea)
After Refresh (Navigating to page by direct link):
![image](https://github.com/DioxusLabs/dioxus/assets/73496400/a6eb68b5-b5e4-427e-9739-1485eeb36f34)

**Environment:**
 - Dioxus version: 0.4.3
 - Dioxus Router version: 0.4.3
    
 - Rust version: 1.74.1
 - OS info: Ubuntu 22.04.3 LTS
 - App platform: Web
 - Browser: Firefox

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later
- [X] I'm interested in potentially contributing to this framework in the future, but I want to focus on using it for now
