### ISSUE TITLE
Latest dioxus master branch renders empty view with odd menus instead of app

### ISSUE THREAD

**Issue by tirithen** [DioxusLabs/dioxus#1864]
**Problem**

Running desktop apps with the latest dioxus and dioxus-desktop master branch commits renders an empty view with a menu instead of the app components/view.

When I run the same code with the released 0.4.3 dependency versions of dioxus and dioxus-desktop the app renders as expected again.

My purpose was that I wanted to experiment with some minor changes in dioxus core for example with the events and possibly suggest back improvements as part of exploring how the project could be used for some project ideas I'm exploring.

Has the code changed significantly since the 0.4.3 release and is this something that could be fixed so that master can render the actual application code instead of the empty view? It would be nice of possible to be able to try out small changes to the code while also working from the latest master branch.

![Skärmbild från 2024-01-24 09-28-46](https://github.com/DioxusLabs/dioxus/assets/245811/7c9fa7cb-1a5b-4cdb-97b1-5f5384257b8a)

And thanks for an interesting project by the way! :-)

**Steps To Reproduce**

1. Copy the dog-app directory from the examples-projects to a separate place
2. Change Cargo.toml to:

```toml
[dependencies]
dioxus = { git = "https://github.com/DioxusLabs/dioxus.git", package = "dioxus" }
dioxus-desktop = { git = "https://github.com/DioxusLabs/dioxus.git", package = "dioxus-desktop" }
```

3. For quick test remove component code that are no longer compliant with API changes, make src/main.rs contain:

```rust
#![allow(non_snake_case)]

use dioxus::{html::input_data::keyboard_types::Key, prelude::*};
use dioxus_desktop::{Config, WindowBuilder};

use crate::models::{list_all_breeds, random_image_by_breed};
mod models;

fn main() {
    dioxus_desktop::launch_cfg(
        app,
        Config::default().with_window(
            WindowBuilder::new()
                .with_maximized(true)
                .with_title("Dog App"),
        ),
    )
}

fn app(cx: Scope) -> Element {
    let selected_breed = use_state::<Option<String>>(cx, || None);
    let search_input = use_state(cx, String::new);

    // Fetch the dog list when the component mounts
    let fut = use_future!(cx, |()| async move { list_all_breeds().await });

    render!(
        link {
            rel: "stylesheet",
            href: "https://unpkg.com/tailwindcss@^2.0/dist/tailwind.min.css"
        }
        div {
            nav { class: "bg-white shadow p-8 border-b border-gray-400 sticky top-0",
                div { class: "flex justify-center align-vertical",
                    input {
                        class: "p-4 w-full",
                        "type": "text",
                        value: "{search_input}",
                        placeholder: "Search for doggo",
                        oninput: move |evt| search_input.set(evt.value().clone()),
                        onkeydown: move |evt| { if evt.key() == Key::Enter {} }
                    }
                }
            }
        }
    )
}

#[allow(non_snake_case)]
#[component]
fn Card<'a>(cx: Scope, title: String, list: Vec<String>, onclick: EventHandler<'a>) -> Element {
    render!(
        div {
            onclick: |_| onclick.call(()),
            class: "my-2 bg-gray-100 w-full rounded-lg p-4 hover:bg-gray-200 ease-in-out duration-75",
            h3 { class: "text-1xl", "{title}" }
            ul { class: "list-disc ml-8",
                {list.iter().map(|item| rsx!( li {
                    key: "{item}",
                    "{item}"
                }))}
            }
        }
    )
}
```
4. Run the project with `$ cargo run` 

**Expected behavior**

The app should render an HTML input element.

**Screenshots**

![Skärmbild från 2024-01-24 09-28-46](https://github.com/DioxusLabs/dioxus/assets/245811/7c9fa7cb-1a5b-4cdb-97b1-5f5384257b8a)

**Environment:**
 - Dioxus version: [`master`]
 - Rust version: [1.75.0]
 - OS info: [Arch Linux 6.7.0-arch3-1 with Gnome 43.5 X11]
 - App platform: [`desktop`]

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by tirithen** [comment]
Thank you for the help and hints!

I copy pasted the main.rs application code you posted, and tried that with the following Cargo.toml file:

```toml
[package]
name = "dog-app"
version = "0.1.1"
edition = "2021"
description = "Search the Dog CEO API for your favorite doggo"
license = "MIT/Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
documentation = "https://dioxuslabs.com"
keywords = ["dom", "ui", "gui", "react", "wasm"]

[dependencies]
dioxus = { git = "https://github.com/DioxusLabs/dioxus.git", package = "dioxus" }
dioxus-desktop = { git = "https://github.com/DioxusLabs/dioxus.git", package = "dioxus-desktop" }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }

[package.metadata.bundle]
name = "Dog Search Engine"
identifier = "com.jon.dogsearch"
version = "1.0.1"
copyright = "Copyright (c) Jane Doe 2016. All rights reserved."
category = "Developer Tool"
short_description = "An example application."
long_description = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
eiusmod tempor incididunt ut labore et dolore magna aliqua.  Ut
enim ad minim veniam, quis nostrud exercitation ullamco laboris
nisi ut aliquip ex ea commodo consequat.
"""
# deb_depends = ["libgl1-mesa-glx", "libsdl2-2.0-0 (>= 2.0.5)"]
# osx_frameworks = ["SDL2"]
```

Then I run with `$ cargo run`, as mentioned before. I tried with both Gnome with X11, and Gnome with Wayland.

When I run on X11 the app starts, but renders the wrong and empty view:

![Skärmbild från 2024-01-24 22-20-39](https://github.com/DioxusLabs/dioxus/assets/245811/df373569-1200-44e3-bd21-5eaf1b4607e5)

When I run with Wayland I get an error, that possibly originates from one of the dioxus dependencies.

```
warning: unused variable: `selected_breed`
  --> src/main.rs:25:9
   |
25 |     let selected_breed = use_state::<Option<String>>(cx, || None);
   |         ^^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_selected_breed`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: unused variable: `fut`
  --> src/main.rs:29:9
   |
29 |     let fut = use_future!(cx, |()| async move {
   |         ^^^ help: if this is intentional, prefix it with an underscore: `_fut`

warning: field `message` is never read
  --> src/main.rs:61:5
   |
60 | struct DogApi {
   |        ------ field in this struct
61 |     message: String,
   |     ^^^^^^^
   |
   = note: `DogApi` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis
   = note: `#[warn(dead_code)]` on by default

warning: `dog-app` (bin "dog-app") generated 3 warnings (run `cargo fix --bin "dog-app"` to apply 2 suggestions)
    Finished dev [unoptimized + debuginfo] target(s) in 53.34s
     Running `target/debug/dog-app`
thread 'main' panicked at /home/user/.cargo/git/checkouts/dioxus-1e619ce595d3799d/b1921cf/packages/desktop/src/webview.rs:134:39:
called `Result::unwrap()` on an `Err` value: UnsupportedWindowHandle
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I tried searching for "UnsupportedWindowHandle" but had a hard time finding the origin of the error.

After this, I tried changing the dependency version back to 0.4.3, and I also changed `.value()` to `.value` and removed the `Key::Enter {}` line just to have it compile.

```toml
[dependencies]
dioxus = "0.4.3"
dioxus-desktop = "0.4.3"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
```

Then the view renders along with the dev tools:

![Skärmbild från 2024-01-24 22-36-58](https://github.com/DioxusLabs/dioxus/assets/245811/da317a10-16e6-4d95-9e42-435d5e8fe3d6)

As seen in the console in the dev tools it seem to use a webkit web view rather than the most recent Chromium/Firefox that is also available on my system, the visual style in the dev tools looks more like mac Safari that is based on webkit, but I suppose that is expected as I find a webkit2gtk and webkit2-sys crates referenced in the `Cargo.lock` file.

In my Arch system package manager I can see version 2.42.4 of webkit2gtk installed which is likely the one being used by the crate with the same name:

```
extra/webkit2gtk-4.1 2.42.4-2 (27.4 MiB 108.0 MiB) (Installerad)
    Web content engine for GTK
extra/webkit2gtk 2.42.4-2 (27.4 MiB 107.9 MiB) (Installerad)
    Web content engine for GTK
```

So all in all, with version 0.4.3 I can see the app and the dev tools, with the latest master branch and Wayland the app crashes, and with the older X11 it starts BUT with the wrong empty view.

Have you bumped versions of some web view crates since the last release? Crates like wry, webkit2gtk or similar? Not that I'm an expert on either of these, but maybe I could try around some more with various versions of these crates if I can get any hints from you which crate dependencies that had major changes since release 0.4.3. Maybe the problem could originate in those dependencies? Or is it more likely in the integration of them?
