### ISSUE TITLE
Add example for multi target Cargo.toml

### ISSUE THREAD

**Issue by mattangus** [DioxusLabs/dioxus#1954]
## Specific Demand

I would like to build my application for different targets and condition them off of the `target_arch` and `target_os`. This is easy enough for web and desktop. For example with the following inside `Cargo.toml`

```toml
[target.'cfg(target_arch = "wasm32")'.dependencies]
dioxus-web = "0.4.3"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
dioxus-desktop = "0.4.3"
```

and the following inside `main`

```rust
#[cfg(not(target_arch = "wasm32"))]
dioxus_desktop::launch(App);

#[cfg(target_arch = "wasm32")]
dioxus_web::launch(App);
```

However the default `Cargo.toml` after running `cargo mobile init` is somewhat complex and it's not clear how to accommodate all three. It would be great to have an example in the documentation `getting started` page for setting up a build environment for a scenario like this.

## Implement Suggestion

I'll try to come up with a working `Cargo.toml` and post it here, but it will likely only work for desktop, web and android (as those are the three I wish to target for my project).
