### ISSUE TITLE
[Desktop] Asset inclusion not working

### ISSUE THREAD

**Issue by Anonyfox** [DioxusLabs/dioxus#2345]
**Problem**

**Steps To Reproduce**

- new desktop app with `dx new`
- with router
- vanilla css
- - dx serve

... the CSS from main.css is not loaded at all. 

- tried more explicit with setting in `Dioxus.toml`: 

```toml
...
# include `assets` in web platform
[web.resource]

# CSS style file

style = ["assets/main.css"]

# Javascript code file
script = []
...
```

no difference. 

- after some tweaking with the paths, I also get (consistently) the error: 

```sh
[ERROR] dioxus_desktop::protocol - Failed to read "/path/to/my/crate/dist/dist/__assets_head.html": No such file or directory (os error 2)
```

where it clearly adds the `/dist` part twice. the file _does_ exist in the dist folder at the correct location on my disk, no idea whats wrong here. no idea whats wrong. No success with removing that error so far. 

**Expected behavior**

**Screenshots**

![Bildschirmfoto 2024-04-19 um 20 33 53](https://github.com/DioxusLabs/dioxus/assets/1140758/67c11dc1-e4a8-4c50-85bf-9a11e5067bea)

**Environment:**
 - Dioxus version: v0.5
 - Rust version:  rustc 1.77.2 (25ef9e3d8 2024-04-09)
 - OS info: MacOS Sonoma 14.4
 - App platform: `desktop`]

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later
