### ISSUE TITLE
`dx build --release` doesn't read the `[profile.release]` table from `Cargo.toml` (`strip` doesn't work)

### ISSUE THREAD

**Issue by Andrew15-5** [DioxusLabs/dioxus#2352]
**Problem**

`strip` setting for release profile doesn't change the binary's file size, even though I checked the [docs](https://doc.rust-lang.org/cargo/reference/profiles.html#strip) (and [this](https://doc.rust-lang.org/rustc/codegen-options/index.html#strip)) and it should change the binary even if by a few bytes. But it doesn't work. Or maybe normally doesn't work (I think once it did change something, but maybe not). It only works via `RUSTFLAGS='-C strip=symbols'`.

**Steps To Reproduce**

1. create a project with `dx new` (Desktop+Tailwind)
1. `cd project_name`
1. add this to the `Cargo.toml`:

  ```toml
  [profile.release]
  # strip = "none"
  # strip = "debuginfo"
  strip = "symbols"
  ```

1. run `dx build -r`
1. see the binary size (`du -b ./dist/binary_name`)
1. change the `strip`'s value as the binary's size shouldn't change
1. prepending `RUSTFLAGS='-C strip=symbols'` will apply the correct `strip` level

**Expected behavior**

`strip` setting for release profile should change binary's file size.

**Environment:**
 - Dioxus version: v0.5.4
 - Rust version: 1.79.0-nightly
 - OS info: Pop!_OS
 - App platform: desktop

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start (pretty sure the fix should be trivial)
- [ ] I would like to fix and I have a solution
- [x] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
Dioxus doesn't read or modify your `Cargo.toml`. It uses cargo to build your project with the settings in your `Cargo.toml`.

Do you see a change in binary size when building with cargo directly?

**Comment by Andrew15-5** [comment]
I didn't try the cargo-direct method, only with/without env var and config changes.

**Comment by ealmloff** [comment]
We use `option_env!()` to import some configuration by for desktop apps if you build with the CLI so that desktop settings like the window name are copied from the `dioxus.toml`. I would expect the binary size to be slightly larger when you build with the CLI because of that.

The difference between strip and no strip in dioxus and cargo seems pretty similar (-162040 in dx) (-157944 in cargo) so this doesn't seem like a bug in dioxus. 

If you would like to minimize the size of your release binary, there are several other settings you can add to your `.cargo/config.toml` described in the [optimization section](https://dioxuslabs.com/learn/0.5/cookbook/optimizing) of the reference:
```toml
[unstable]
build-std = ["std", "panic_abort", "core", "alloc"]
build-std-features = ["panic_immediate_abort"]

[build]
rustflags = [
    "-Clto",
    "-Zvirtual-function-elimination",
    "-Zlocation-detail=none"
]

# Same as in the Stable section
[profile.release]
opt-level = "z"
debug = false
lto = true
codegen-units = 1
panic = "abort"
strip = true
incremental = false
```

When building with nightly and those settings, the tailwind desktop bundle goes from ~5mb to ~2mb for a macOS ARM

Closing this issue as not reproducable
