### ISSUE TITLE
head::Link creates link twice with SSR

### ISSUE THREAD

**Issue by ochrons** [DioxusLabs/dioxus#2885]
**Problem**

When application does server side rendering, the `link` tag in the head is created once by the server and sent to browser in the HTML, but then created again when the WASM code is executed, resulting in two identical elements.

**Steps To Reproduce**

- add `head::Link { rel: "stylesheet", href: "public/test.css" }` to your main RSX
- use SSR

**Expected behavior**

The head element should only be created once on the server, not again on the client.

**Environment:**
 - Dioxus version:  0.6.0-alpha.2
 - Rust version:    stable
 - OS info:         Win11 WSL
 - App platform:    fullstack

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
I cannot reproduce this issue anymore with the steps you posted. This code only renders the link once in the head:

Cargo.toml:
```toml
[dependencies]
dioxus = { git = "https://github.com/DioxusLabs/dioxus", features = ["fullstack"] } 

[features]
web = ["dioxus/web"]
server = ["dioxus/server"]
```
main.rs:
```rust
use dioxus::prelude::*;

fn main() {
    launch(App);
}

#[component]
fn App() -> Element {
    rsx! {
        head::Link { rel: "stylesheet", href: "public/test.css" }
        HasStyles {}
    }
}

fn HasStyles() -> Element {
    rsx! {
        head::Link { rel: "stylesheet", href: "public/test.css" }
    }
}
```
