### ISSUE TITLE
`dx bundle` does not work.

### ISSUE THREAD

**Issue by TheAlexDev23** [DioxusLabs/dioxus#2941]
**Problem**

When running `dx bundle` on an application with resources configured in the bundle section within Dioxus.toml, it panics with the following message:

```rust
  👑 Build done.                                                                                                                                                                                                   build desktop done
Adding assets from dist to bundle
thread 'main' panicked at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-bundler-1.4.0/src/bundle/settings.rs:749:29:
cannot use both `resources` and `resources_map`
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: tauri_bundler::bundle::settings::Settings::copy_resources
   3: tauri_bundler::bundle::linux::debian::generate_data
   4: tauri_bundler::bundle::linux::debian::bundle_project
   5: tauri_bundler::bundle::bundle_project
   6: dioxus_cli::cli::bundle::Bundle::bundle
   7: tokio::runtime::park::CachedParkThread::block_on
   8: dx::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Here's Dioxus.toml:
```toml
[application]

# App (Project) Name
name = "frontend"

# Dioxus App Default Platform
# desktop, web
default_platform = "desktop"

# `build` & `serve` dist path
out_dir = "dist"

# assets file folder
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "frontend"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

# include `assets` in web platform
[web.resource]

# CSS style file

style = []

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
resources = ["color.css", "custom-elements.css", "main.css", "icons/*"]
```

**Environment:**
 - Dioxus version:  0.5.6
 - dioxus-cli version: 0.5.7
 - Rust version:   rustc 1.80.0
 - OS info: Linux
 - App platform:  desktop
