### ISSUE TITLE
`user-select: none` isn't being applied through CSS style (must add manually to every element)

### ISSUE THREAD

**Issue by Andrew15-5** [DioxusLabs/dioxus#3424]
**Problem**

I tried adding

```css
input[typ="button"], button {
  user-select: none;
}
```

to `main.css`, but it did not remove text selection even after manual rebuild. But it does work if I do:

```css
input[typ="button"], button {
  color: red;
}
```

So it seems that the issue is with that particular property.

**Steps To Reproduce**

- get project from https://gitlab.com/Andrew15-5/dioxus-test-todo-app
- try removing all the `select-none` classes and instead use CSS selectors to do the same
- the text is still selectable even after rebuilding with `r` in `dx serve`

**Expected behavior**

Text isn't selectable for the specified elements.

**Screenshots**

**Environment:**

 - Dioxus version: v0.6.1
 - Rust version: rustc 1.83.0-nightly (fb4aebddd 2024-09-30)
 - OS info: Pop!_OS 22.04
 - App platform: desktop

**Questionnaire**

I'm interested in fixing this myself but don't know where to start.
I don't have time to fix this right now, but maybe later.
