### ISSUE TITLE
TailwindCSS `flex-col` class doesn't work with `dx` `serve`/`build`

### ISSUE THREAD

**Issue by Andrew15-5** [DioxusLabs/dioxus#3432]
**Problem**

[Context](https://discord.com/channels/899851952891002890/928812591126569000/1320425789308669993)

For some weird reason `flex-col` class doesn't have any effect:

```rs
#[component]
pub fn Navbar() -> Element {
    rsx! {
        document::Link { rel: "stylesheet", href: NAVBAR_CSS }

        div {
            id: "navbar",
            class: "flex flex-col",
```

**Steps To Reproduce**

- get project from [flex-col.zip](https://github.com/user-attachments/files/18222677/flex-col.zip)
- try `dx serve` or `dx build` to work with `flex-col`

**Expected behavior**

div children of the flex div are arranged into a column, i.e., one under another.

**Screencast**

https://github.com/user-attachments/assets/7c187028-8e27-4b49-9810-aa555c7aae05

**Environment:**
 - Dioxus version: v0.6.1
 - Rust version: rustc 1.83.0-nightly (fb4aebddd 2024-09-30)
 - OS info: Pop!_OS
 - App platform: web

**Questionnaire**

I'm interested in fixing this myself but don't know where to start.
I don't have time to fix this right now, but maybe later.

**Comment by Andrew15-5** [comment]
And just like that, I tried to workaround it with CSS, and then I see:

```css
#navbar {
  display: flex;
  /* background: red; */
  gap: 15px;
  flex-direction: row;
  justify-content: center;
  /* align-items: center; */
  margin-bottom: 20px;
}
```
