### ISSUE TITLE
Hope to add sass module support

### ISSUE THREAD

**Issue by sbfkcel** [DioxusLabs/dioxus#3490]
## Feature Request

This will isolate the style of each component very well, and Sass can also make writing CSS faster.

## Implement Suggestion

```rust
static styles: Asset = asset!("/assets/component.module.scss");
rsx! {
    div {
        class: styles.box
    }
}
```

**Comment by oovm** [comment]
It looks like the cli already has a function for compiling scss:

https://github.com/DioxusLabs/dioxus/blob/main/packages/cli-opt/src/css.rs

However, it would be more convenient and more in line with cognition if `asset!` could support scss.

**Comment by DogeDark** [comment]
@oovm `asset!` does support SCSS, but not SCSS modules. CSS modules are being worked on in #3578, which SCSS modules could be built on top of.

**Comment by tryoxiss** [comment]
It seems to kinda support sass modules, I just did a quick test:

```scss
// test.scss, linked via asset!

@use 'module' as *;

// Yes, it seems SCSS and most importantly @use can work in the bundler!
// That means I need to migrate all my plain styles to SCSS.

@mixin blue {
  background-color: blue;
}

.bg-blue {
  @include blue;
}

.bg-green {
  @include green;
}
```

and then

```scss
// module.scss, only liked in the test.scss file, never in the rust

@mixin green {
  background-color: green;
}
```

It works, sort of. When first running `dx serve`, it links everything properly and the test green BG works just fine, so does the blue. When I change either SCSS file though, it seems to not recompile either SCSS so it results in those styles disappearing entirely. (EDIT: This also seems to be the case even when having only one SCSS file, I completely removed the second one and this still happens...)

So it defintely doesn't support sass modules at an acceptable DX, but it does sort of work. I point this out as it points to possibly it just being a bug that it isn't supported, as it works sometimes.
