### ISSUE TITLE
dx-cli-0.6.2 outputs MIME issue.

### ISSUE THREAD

**Issue by abhi3700** [DioxusLabs/dioxus#3669]
**Problem**

When switching from 0.6.1 to 0.6.2, I found that the web app opened `dx serve` doesn't open the page because of MIME issue.

**Steps To Reproduce**

- `$ dx serve`

I can share the `Dioxus.toml`:

```toml
[application]

# App (Project) Name
name = "unifi"

[web.app]

# HTML title tag content
title = "UniFi"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
```

& 

`index.html`:
```html
<!DOCTYPE html>
<html>
  <head>
    <title>UniFiUniFiUniFi</title>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta charset="UTF-8" />
  <link rel="preload" href="/./wasm/unifi-web-app_bg.wasm" as="fetch" type="application/wasm" crossorigin="">
            <link rel="preload" href="/./wasm/unifi-web-app.js" as="script">
            </head>
  <body>
    <div id="main"></div>
  <script>
            // We can't use a module script here because we need to start the script immediately when streaming
            import("/./wasm/unifi-web-app.js").then(
                ({ default: init }) => {
                init("/./wasm/unifi-web-app_bg.wasm").then((wasm) => {
                    if (wasm.__wbindgen_start == undefined) {
                    wasm.main();
                    }
                });
                }
            );
            </script>
            
            </body>
</html>
```

This is how target folder looks like with `0.6.2`:
![Image](https://github.com/user-attachments/assets/1e954b4c-c514-41be-8f6a-ebf988c8a97d)

And with `0.6.1`:

![Image](https://github.com/user-attachments/assets/b30baf0a-5417-404b-ba77-37fd76b44571)

**Expected behavior**

Web page should have been opened with required design.

**Screenshots**

This is how it looks like currently with dx-cli-0.6.2:
![Image](https://github.com/user-attachments/assets/43e892dc-bfa9-4ce5-b0b5-6f6c4c57b75c)

And expected is (getting with dioxus-0.6.1):

<img width="1237" alt="Image" src="https://github.com/user-attachments/assets/5608e75e-4636-4a2d-b01f-a528ccfbc5f5" />

**Environment:**
 - Dioxus version:  v0.6.2
 - Rust version: 1.83.0
 - OS info: MacOS
 - App platform:`web`

**Questionnaire**
