### ISSUE TITLE
Server state other than a global ?

### ISSUE THREAD

**Issue by azr** [DioxusLabs/dioxus#3876]
Hello there ! Interesting project !!

I've been playing with the fullstack + fully featured boilerplate app on `v0.6.3`
I wanted to have my own specific state, but I have to create weird code to do so.
My question is in the code :

```rust
// server/src/lib.rs
use dioxus::prelude::*;

#[cfg(feature = "server")]
mod state {
    use sqlx::SqlitePool;

    pub struct State {
        pub pool: SqlitePool,
    }

    impl State {
        pub async fn new() -> Self {
            let pool = SqlitePool::connect("sqlite::memory:").await.unwrap();
            Self { pool }
        }
    }
}

/// Echo the user input on the server.
#[server]
pub async fn echo(input: String) -> Result<String, ServerFnError> {
    #[cfg(feature = "server")] // <------------------- HOW TO REMOVE THIS ?
                               // If I remove this check, rust :
                               // 24 |     let _ = state::State::new().await;
                               //    |             ^^^^^ use of undeclared crate or module `state`
                               // But sqlx/tokio/etc. cannot be compiled for the frontend
    let _ = state::State::new().await;
    Ok(input)
}
```

Shouldn't the frontend part ignore the content of the echo function on its own ?
And treat it basically like `{ todo!() }` and only care about the signature ?

The example in the server tag looks like so:

```rust
use dioxus::prelude::*;
fn app() -> Element { unimplemented!() }
#[derive(Clone, Copy, Debug)]
struct DatabasePool;

fn main() {
    LaunchBuilder::new()
        .with_context(server_only! {
            DatabasePool
        })
        .launch(app);
}

#[server]
pub async fn my_wacky_server_fn(input: Vec<String>) -> Result<String, ServerFnError> {
    let FromContext(pool): FromContext<DatabasePool> = extract().await?;
    Ok(format!("The server read {:?} from the shared context", pool))
}
```

But I'm guessing that wouldn't work if DatabasePool got complicated ? Would it ?

**Comment by ealmloff** [comment]
Make sure you forward the server feature from your `server` crate through your `ui` and `web` crates:
```toml
# server crate
# ...
[features]
server = ["dependencies"]
```

```toml
# ui crate
# ...
[features]
server = ["server/server"]
```

```toml
# web crate
# ...
[features]
server = ["ui/server", "dioxus/server"]
```

If you don't want to use global state, you can use the context approach with whatever state you need to access in server functions. It may be easier to keep most of the server side logic for your context type under a server only module in your server crate as described [here](https://dioxuslabs.com/learn/0.6/guides/fullstack/managing_dependencies#managing-binary-specific-imports) in the docs.

**Comment by azr** [comment]
Hey @ealmloff thanks so much, changing my setting to the following solved it :

```toml
[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["router"] }
ui = { workspace = true, optional = true }

[features]
default = []
web = ["dioxus/web", "ui"]
server = ["dioxus/server", "ui/server"]
```
