### ISSUE TITLE
CSS modules can't handle prefixes

### ISSUE THREAD

**Issue by CryZe** [DioxusLabs/dioxus#4028]
**Problem**

If I have a CSS module like so:

```css
.sidebar { 
    background: red;
    padding: 20px;
}
.sidebarButton {
    background: blue;
}
```

then the `Classes::sidebar_button` class doesn't actually work. The reason is that because it has the same `sidebar` prefix as an already mangled class, it mangles the name twice on accident.

```css
.sidebarfb811ee670c8c644 {
    background: red;
    padding: 20px
}

.sidebarfb811ee670c8c644Button {
    background: #00f
}
```

in the DOM:

```html
<div class="sidebarfb811ee670c8c644">
    <button class="sidebarButtonfb811ee670c8c644">Hi</button>
</div>
```

**Steps To Reproduce**

```rust
css_module!(Classes = "/assets/sidebar.css");

#[component]
pub fn Sidebar() -> Element {
    rsx! {
        div { class: "{Classes::sidebar}",
                button { class: "{Classes::sidebar_button}", "Hi" }
            }
    }
}
```

**Expected behavior**

The button should be blue.

**Screenshots**

![Image](https://github.com/user-attachments/assets/02ff3ff8-b665-4cb0-ab74-7c576f291856)

**Environment:**

- Dioxus version:  main@1001d78c7fbf717df50e9209513b03676e03635c
- Rust version:    1.86
- OS info:        Windows 11
- App platform:    desktop

**Questionnaire**

I'm interested in fixing this myself but don't know where to start.
