### ISSUE TITLE
CSS list-style does not work as expected

### ISSUE THREAD

**Issue by oawd** [DioxusLabs/dioxus#4058]
I have written a list in RSX and want to style it with CSS.

In the CSS file this works:
```css
#list ul {
    list-style: square;
}
``` 

But this does not work:
```css
#list ul {
    list-style: url("item-marker.png");
}
``` 
The file `item-marker.png` is in the same folder as the CSS file.
Am I doing something wrong or is this CSS feature not available in Dioxus?

**Environment:**

- Dioxus version:  0.6.3
- Rust version:    1.86.0
