### ISSUE TITLE
RSX `style` element causes runtime error while style attribute works correctly

### ISSUE THREAD

**Issue by bigg-S** [DioxusLabs/dioxus#4068]
When using the `style` element inside the `rsx!` macro, I encounter a JavaScript Runtime error. However, using the `style` attribute as a property works correctly.

**Comment by jjvn84** [comment]
@bigg-S What is the content of "css_variables"?

**Comment by bigg-S** [comment]
when I used the `style` element `css_variables` value was as below:

```css
#scoped-theme { --primary: #0070f3; --primary-foreground: white; --secondary: #383838; --secondary-foreground: white; --accent: #7928CA; --accent-foreground: white; --bg-color: #fff; --foreground: #000; --card: #f9f9f9; --card-foreground: #111; --border: #eaeaea; --ring: #BBBBBB; --destructive: #ef4444; --destructive-foreground: #fff; --muted: #f3f4f6; --muted-foreground: #64748b;  --font-sans: Times New Roman; --font-heading: Helvetica, sans-serif; --font-size-base: 16px; --line-height-normal: 1.5;    --font-weight-bold: 700;   --font-weight-normal: 700;   --font-weight-semibold: 800;   --font-weight-light: 300;   --font-weight-medium: 500;  --spacing-unit: rem;   --spacing-0: 0px;   --spacing-2: 0.5rem;   --spacing-1: 0.25rem;   --spacing-16: 4rem;   --spacing-3: 0.75rem;   --spacing-5: 1.25rem;   --spacing-8: 2rem;   --spacing-4: 1rem;   --spacing-10: 2.5rem;   --spacing-6: 1.5rem;   --spacing-12: 3rem;  --radius-sm: 0.125rem; --radius-md: 0.25rem; --radius-lg: 0.5rem; --radius-xl: 1rem; --radius-full: 9999px;  --shadow-sm: 0 1px 2px 0 rgb(0 0 0 / 0.05); --shadow-md: 0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.05); --shadow-lg: 0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.05); --shadow-xl: 0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.05); --shadow-2xl: 0 25px 50px -12px rgb(0 0 0 / 0.25); }
```

but for the `style` attribute, I used it this way:

```css

--primary: #0070f3; --primary-foreground: white; --secondary: #383838; --secondary-foreground: white; --accent: #7928CA; --accent-foreground: white; --bg-color: #fff; --foreground: #000; --card: #f9f9f9; --card-foreground: #111; --border: #eaeaea; --ring: #BBBBBB; --destructive: #ef4444; --destructive-foreground: #fff; --muted: #f3f4f6; --muted-foreground: #64748b;  --font-sans: Times New Roman; --font-heading: Helvetica, sans-serif; --font-size-base: 16px; --line-height-normal: 1.5;    --font-weight-bold: 700;   --font-weight-normal: 700;   --font-weight-semibold: 800;   --font-weight-light: 300;   --font-weight-medium: 500;  --spacing-unit: rem;   --spacing-0: 0px;   --spacing-2: 0.5rem;   --spacing-1: 0.25rem;   --spacing-16: 4rem;   --spacing-3: 0.75rem;   --spacing-5: 1.25rem;   --spacing-8: 2rem;   --spacing-4: 1rem;   --spacing-10: 2.5rem;   --spacing-6: 1.5rem;   --spacing-12: 3rem;  --radius-sm: 0.125rem; --radius-md: 0.25rem; --radius-lg: 0.5rem; --radius-xl: 1rem; --radius-full: 9999px;  --shadow-sm: 0 1px 2px 0 rgb(0 0 0 / 0.05); --shadow-md: 0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.05); --shadow-lg: 0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.05); --shadow-xl: 0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.05); --shadow-2xl: 0 25px 50px -12px rgb(0 0 0 / 0.25);
```
