### ISSUE TITLE
Subsecond fails linking when combining mold + a global target dir

### ISSUE THREAD

**Issue by janhohenheim** [DioxusLabs/dioxus#4149]
**Problem**

I use a highly optimized `~/.cargo/config.toml`, and it seems like a certain combination of features results in subsecond failure:

```
22:46:38 [dev] Failed to generate fat binary: mold: fatal: /home/hhh/.cargo/global-target/x86_64-unknown-linux-gnu/debug/libfatdependencies-f8b34a0a-074d-5f6c-bfcc-ab596collect2: error: ld returned 1 exit status
```

**Steps To Reproduce**

- Clone https://github.com/jkelleyrtp/subsecond-bevy-demo
- Create a file in `.cargo/config.toml` with the following content (replace `hhh` with your username):
```toml
[build]
target-dir = "/home/hhh/.cargo/global-target"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
  # Linker
  "-C",
  "link-arg=-fuse-ld=mold",
]
```
- `mkdir ~/.cargo/global-target/`
- `ln -s /usr/bin/mold /usr/bin/ld` (see #4144)
  - The same happens when using `ln -s /usr/bin/lld /usr/bin/ld`
- `dx serve --hot-reload`

**Expected behavior**

The app to start.
Note that this is fixed by either
- Commenting out the `target-dir` key
  - Not desirable, as that disables the global cache
- Replacing the line `"link-arg=-fuse-ld=mold"` with `"link-arg=-fuse-ld=lld`
  - Not desirable, as that reduces linking performance

As a workaround for now, one can remove the `target-dir` and do
```sh
ln -s /home/foo/global-target target
```

**Screenshots**

**Environment:**

- Dioxus version: `dioxus 0.7.0-alpha.0 (48e925f)`
- Rust version:   `rustc 1.89.0-nightly (ce7e97f73 2025-05-11)`
- OS info:        `Fedora release 42 (Adams)`
- App platform:    `Desktop Linux`
