### ISSUE TITLE
Don't insert configuration into `Cargo.toml` when using the CLI just for hot-patching / subsecond

### ISSUE THREAD

**Issue by janhohenheim** [DioxusLabs/dioxus#4168]
## Feature Request

Running `dx serve --hot-patch` adds the following to my `Cargo.toml`:
```toml
[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
```
As a Bevy user, these don't make sense to me, as the Bevy CLI alpha has its own profile for Wasm deployments, my game is single-player, and I do not support Android 😉
