### ISSUE TITLE
Subsecond fails to compile with --ld-path linker arg

### ISSUE THREAD

**Issue by TapGhoul** [DioxusLabs/dioxus#4196]
**Problem**

Subsecond happily supports -fuse-ld, however it fails with "--ld-path" when using `dx serve --hotpatch`
They should ideally both be supported. As of Clang 12, using -fuse-ld with a full path (as opposed to just a linker name) is a warning, and --ld-path is its replacement for that use case.

This was needed to add support for custom linkers that are not built into gcc/clang's known linker list, back when mold was new. It is now supported properly, but is still important if you don't want to symlink linkers around for newer linkers that haven't yet gotten upstreamed support.
Afaik the main reason for this flag is that clang plans to change behavior of what is fed to the linker based on the linker being used, or at least they wish to reserve the right to - which is why they have a separate flag that changes just the path and can guarantee no side effects.

**Steps To Reproduce**

- Set up your `.cargo/config.toml` to include `rustflags = ["-Clink-arg=--ld-path=/usr/bin/mold"]` (or any other linker)
- Broken
A full example file (what I use):
```toml
[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-Clink-arg=--ld-path=/usr/bin/mold", "-Ctarget-cpu=native"]
```
A working, but not entirely equal example:
```toml
[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-Clink-arg=-fuse-ld=mold", "-Ctarget-cpu=native"]
```

**Expected behavior**

A successful build, same as `dx serve` on its own

**Environment:**

- Dioxus version:  0.7.0-alpha.0
- Rust version:    1.87.0
- OS info:         Arch Linux latest
- App platform:    Dioxus CLI with subsecond inside a basic hello world

**Questionnaire**

I'm interested in fixing this myself but don't know where to start.
