### ISSUE TITLE
Subsecond does not respect rustflags cfg settings from .cargo/config.toml (getrandom fails to build)

### ISSUE THREAD

**Issue by niclashoyer** [DioxusLabs/dioxus#4238]
**Problem**

I thought that #4146 was the same issue and that #4174 would fix the issue with getrandom, but the build still fails for me with `0.7.0-alpha.1` when using linker settings in `.cargo/config.toml`:

```toml
[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']
```

**Steps To Reproduce**

```bash
git clone https://github.com/niclashoyer/dioxus-bug.git
cd dioxus-bug
cargo binstall --version "0.7.0-alpha.1" dioxus-cli --root .
bin/dx serve --hot-patch
```

(`bin/dx serve` without subsecond works)

**Expected behavior**

The build should work with getrandom enabled and hot patching working.

**Environment:**

- Dioxus version: 0.7.0-alpha.1
- Rust version: 1.87.0
- OS info: Fedora Linux 42
- App platform: web/fullstack
