### ISSUE TITLE
Can't make onclick / onkeydown to work...

### ISSUE THREAD

**Issue by dbkblk** [DioxusLabs/dioxus#4278]
**Problem**

I tried for hours to make onclick / onkeydown to work on div, so I made a basic example. Nothing works for me. I see no output in console, when serving with `dx serve`.
I've tried using firefox / chromium on debian.

Is it a bug or am I missing something basic?

**Steps To Reproduce**

main.rs
```rust
use dioxus::prelude::*;

fn main() {
    dioxus::launch(App);
}

#[component]
fn App() -> Element {
    rsx! {
        div {
            onkeyup: |event_data| println!("key up! I got the event data: {event_data:?}"),
            button {
                // The `onclick` event accepts a closure with the signature `fn(Event)`
                onclick: |event_data| println!("clicked! I got the event data: {event_data:?}"),
                "Click me"
            }
        }
    }
}
```

Cargo.toml
```toml
[package]
name = "dioxus_keyboard"
version = "0.1.0"
authors = []
edition = "2021"

[dependencies]
dioxus = { version = "0.6.3", features = ["fullstack", "html"] }

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
```
