### ISSUE TITLE
Example hello_world_tui.rs does not compile

### ISSUE THREAD

**Issue by migepatschen** [DioxusLabs/dioxus#567]
**Problem**

<https://github.com/DioxusLabs/dioxus/blob/master/docs/guide/examples/hello_world_tui.rs> does not compile because `dioxus_tui::` has to be replaced with `dioxus::tui`.

**Steps To Reproduce**

- create Rust project
- copy and paste code
- run `cargo check`

**Expected behavior**

Code should compile.

**Environment:**
 - Dioxus version: `dioxus = { version = "0.2.4", features = ["tui"] }`
 - Rust version: `v1.64.0`
 - OS info: Windows
 - App platform: `tui`

**Questionnaire**
- [ ] I'm interested in fixing this myself but don't know where to start
- [x] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by Demonthos** [comment]
The examples are kept up to date with master, not stable. If you want to see some examples that work on stable, you can navigate to the branch on github: https://github.com/DioxusLabs/dioxus/tree/v0.2.4/examples
Otherwise you can switch to master to make the example compile:
```toml
dioxus = { git = "https://github.com/dioxuslabs/dioxus.git" }
dioxus_tui = { git = "https://github.com/dioxuslabs/dioxus.git" }
```
The master version has renderers separated into crate.
