### ISSUE TITLE
version conflict for `dunce` crate when installing desktop from master

### ISSUE THREAD

**Issue by yusefnapora** [DioxusLabs/dioxus#624]
**Problem**

I got excited about hot reloading in desktop and decided to try kicking the tires a bit. As the features haven't been released, I tried depending on `dioxus` and `dioxus-desktop` from git, targeting the latest commit on `master`. Of course, I don't expect any stability guarantees for `master`, just thought you'd want to know that I hit an issue.

I get the following version conflict:

```
error: failed to select a version for `dunce`.
    ... required by package `wry v0.22.0`
    ... which satisfies dependency `wry = "^0.22.0"` of package `dioxus-desktop v0.2.3 (https://github.com/DioxusLabs/dioxus?rev=f21c8423eb93c20a62261105c2611b4a71e80c7b#f21c8423)`
    ... which satisfies git dependency `dioxus-desktop` of package `lumachromatic v0.1.0 (/home/yusef/projects/lumatone/lumatone-rs/gui)`
versions that meet the requirements `^1.0.3` are: 1.0.3

all possible versions conflict with previously selected packages.

  previously selected package `dunce v1.0.2`
    ... which satisfies dependency `dunce = "^1.0.2"` (locked to 1.0.2) of package `dioxus-desktop v0.2.3 (https://github.com/DioxusLabs/dioxus?rev=f21c8423eb93c20a62261105c2611b4a71e80c7b#f21c8423)`
    ... which satisfies git dependency `dioxus-desktop` of package `lumachromatic v0.1.0 (/home/yusef/projects/lumatone/lumatone-rs/gui)`

failed to select a version for `dunce` which could resolve this conflict
```

**Steps To Reproduce**

- Add the following to Cargo.toml

```toml
dioxus = { git = "https://github.com/DioxusLabs/dioxus", rev = "f21c8423eb93c20a62261105c2611b4a71e80c7b", features = ["macro", "hooks", "html", "hot-reload"] }
dioxus-desktop = { git = "https://github.com/DioxusLabs/dioxus", rev = "f21c8423eb93c20a62261105c2611b4a71e80c7b", features = ["tokio_runtime", "hot-reload"] }
```

- `cargo build`

**Expected behavior**

Deps install without issue.

**Possible solution**

It seems like this is happening because `wry` v0.22.0 depends on `dunce` v1.0.3, but `dioxus-desktop` has `dunce` pinned to 1.0.2. Updating that to `^1.0.3` should hopefully do the trick.

**Environment:**
 - Dioxus version: `master` (`f21c8423eb93c20a62261105c2611b4a71e80c7b`)
 - Rust version: 1.65.0
 - OS info: NixOS 22.05 via WSL2 on Windows 11
 - App platform: `desktop`

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [x] I don't have time to fix this right now, but maybe later
