### ISSUE TITLE
How to include a local font asset

### ISSUE THREAD

**Issue by MauriceKayser** [DioxusLabs/dioxus#750]
There is [examples/custom_assets.rs](https://github.com/DioxusLabs/dioxus/blob/master/examples/custom_assets.rs), which shows how to include local image assets, but no example for fonts. In CSS they need to be included like this:
```css
@font-face {
    font-family: "font-name-here",
    src: url("assets/font.woff2")
}
```
I tried including the CSS in the HTML I use for `dioxus_desktop::launch_cfg() [ ... ] .with_custom_index(include_str!("my_index.html").into())`, but that obviously does not pick up the `assets/font.woff2` part at compile time. I then tried the `rsx!` macro, which recognizes neither of `style { @font-face / @font_face / font-face / font_face { ... } }`.
