### ISSUE TITLE
Is hot reload broken?

### ISSUE THREAD

**Issue by 18601673727** [DioxusLabs/dioxus#862]
Hi, I'm expecting hot reload works on `dioxus-liveview` or `dioxus-ssr` or both with `hot_reload_init!()`, but after couple failed attempts, hot reload is currently only working on `dioxus-web` with git version of `dioxus-cli`. Here's my dioxus versions.

```bash
$ cargo tree | grep dioxus
├── dioxus v0.3.2
│   ├── dioxus-core v0.3.2
│   ├── dioxus-core-macro v0.3.0 (proc-macro)
│   │   ├── dioxus-rsx v0.0.2
│   │   │   ├── dioxus-core v0.3.2
│   ├── dioxus-hooks v0.3.0
│   │   ├── dioxus-core v0.3.2 (*)
│   ├── dioxus-hot-reload v0.1.1
│   │   ├── dioxus-core v0.3.2 (*)
│   │   ├── dioxus-html v0.3.1
│   │   │   ├── dioxus-core v0.3.2 (*)
│   │   │   ├── dioxus-rsx v0.0.3
│   │   │   │   ├── dioxus-core v0.3.2 (*)
│   │   ├── dioxus-rsx v0.0.3 (*)
│   ├── dioxus-html v0.3.1 (*)
│   └── dioxus-rsx v0.0.3 (*)
├── dioxus-liveview v0.3.0
│   ├── dioxus-core v0.3.2 (*)
│   ├── dioxus-html v0.3.1 (*)
│   ├── dioxus-interpreter-js v0.3.1
```
And Cargo.toml
```toml
[dependencies]
tokio = { version = "1.26.0", features = ["full"] }
axum = { version = "0.6.10", features = ["ws"] }
dioxus = { version = "*" }
dioxus-liveview = { version = "*", features = ["axum"] }
pretty_env_logger = "0.4.0"
```
Thank you!

**Comment by Demonthos** [comment]
It appears we need to bump the version of the liveview crate. Hot-reloading with liveview works on the master branch, but the integration does not exist on the published branch. 

Because of how SSR is structured, it does not support hot reloading. To hot reload templates, you need mutable access to the VDom, which the ssr renderer does not require. You can roll your own implementation with the [hot-reload crate](https://lib.rs/crates/dioxus-hot-reload) (see the readme for more info)

**Comment by 18601673727** [comment]
Thanks for the quick help, it did works after changed Cargo.toml like this:
```toml
tokio = { version = "1.26.0", features = ["full"] }
axum = { version = "0.6.10", features = ["ws"] }
dioxus = { git = "https://github.com/DioxusLabs/dioxus" }
dioxus-liveview = { git = "https://github.com/DioxusLabs/dioxus", features = ["axum"] }
pretty_env_logger = "0.4.0"
```
And in main function:
```diff
- hot_reload_init!();
+ hot_reload_init!(Config::new().with_rebuild_command("cargo run"));
```
However, everytime I change something in code, the project re-compiles, and it's kinda long time waiting. So was there any better way to implement this like Flutter or React do? I've got spoiled too much by those and it feels tough to adopt..

**Comment by Demonthos** [comment]
> However, everytime I change something in code, the project re-compiles, and it's kinda long time waiting. So was there any better way to implement this like Flutter or React do? I've got spoiled too much by those and it feels tough to adopt..

Hot reloading rsx has the benefit of not requiring a recompile, but it is definitely limited compared to hot reloading in js frameworks. Unfortunately there isn't a great way to improve this right now. Rust is free to rearrange state in ways that interpreted languages cannot, which makes hot reloading a lot more difficult. You need to define a layer that cannot change between compiles (the dylib api). It is possible to keep the state between recompiles (https://robert.kra.hn/posts/hot-reloading-rust/), but compiling will always be necessary.

**Comment by 18601673727** [comment]
> > However, everytime I change something in code, the project re-compiles, and it's kinda long time waiting. So was there any better way to implement this like Flutter or React do? I've got spoiled too much by those and it feels tough to adopt..
> 
> Hot reloading rsx has the benefit of not requiring a recompile, but it is definitely limited compared to hot reloading in js frameworks. Unfortunately there isn't a great way to improve this right now. Rust is free to rearrange state in ways that interpreted languages cannot, which makes hot reloading a lot more difficult. You need to define a layer that cannot change between compiles (the dylib api). It is possible to keep the state between recompiles (https://robert.kra.hn/posts/hot-reloading-rust/), but compiling will always be necessary.

Could we at least have the frontend acknowledge that a re-compile finishes then refresh the page or rehydrate dom automatically? Because at the moment we have to refresh the page manually after the unavoidable waiting, despite how much longer it would be after dependency list grew.

**Comment by Demonthos** [comment]
Definitely! https://github.com/DioxusLabs/dioxus/pull/762 should make the client reconnect after a recompile

**Comment by alkeryn** [comment]
hey any news on this, hot reload is still not working on desktop, i tried using master for the crate dioxus but i got a compile error i don't get on 0.3.2

**Comment by Demonthos** [comment]
> hey any news on this, hot reload is still not working on desktop, i tried using master for the crate dioxus but i got a compile error i don't get on 0.3.2

What error do you get?

**Comment by alkeryn** [comment]
@Demonthos  i get
```
   |             dioxus_desktop::launch(app)
   |             ---------------------- ^^^ expected struct `dioxus_core::scopes::Scoped`, found struct `Scoped`
```

**Comment by alkeryn** [comment]
Oh ok.
that error wasn't very verbose.
thanks ! :)

**Comment by alkeryn** [comment]
well it now build but still doesn't hot reload, no idea why.

**Comment by TCROC** [comment]
Can confirm that hot reloading doesn't work with the current cargo crate, but pointing to the git repo fixes it:

```toml
[dependencies]
dioxus = { git = "https://github.com/DioxusLabs/dioxus" }
dioxus-desktop = { git = "https://github.com/DioxusLabs/dioxus" }
```

When will an update be pushed out for the crate?

And also, great work!  I really like what I see so far!  It is very ergonomic and easy to use as someone new to rust!
