### ISSUE TITLE
WASM `panicked at 'misaligned pointer dereference`...

### ISSUE THREAD

**Issue by trevyn** [DioxusLabs/dioxus#944]
Affects debug builds on Rust nightly, due to https://github.com/rust-lang/rust/pull/98112

`dioxus create` + `dioxus serve` = console `panicked at 'misaligned pointer dereference: address must be a multiple of 0x4 but is 0x113829', /Users/e/.cargo/git/checkouts/dioxus-1e619ce595d3799d/7c9295a/packages/interpreter/src/sledgehammer_bindings.rs:5:1`

**Comment by gmorenz** [comment]
Note that this is about to hit stable in 1.70

**Comment by dxps** [comment]
I'm currently getting it in the recently released stable 1.70. :thinking:

**Comment by dxps** [comment]
@Demonthos  Thanks for the feedback, but which released version of Dioxus?
Currently I see that [v0.3.2](https://github.com/DioxusLabs/dioxus/releases/tag/v0.3.2) exists.
And if I'm using cargo's `[patch]` feature, how that helps, please?

Concretely speaking, as stated [here](https://github.com/oovm/dioxus-hooks/issues/3), I tried with:
```
dioxus = { git = "https://github.com/DioxusLabs/dioxus.git" }
dioxus-web = { git = "https://github.com/DioxusLabs/dioxus.git" }
dioxus-router = { git = "https://github.com/DioxusLabs/dioxus.git", features = [ "web" ] }
```

which would work. Now I'd either wait for `dioxus-use-storage` dependency to get updated or create a PR for it.

**Comment by Demonthos** [comment]
The release that fixed this issue was https://crates.io/crates/sledgehammer_bindgen/0.2.2 which was bumped by https://crates.io/crates/dioxus-interpreter-js/0.3.3.

The patch section should be as simple as:
```toml
[patch]
dioxus = { git = "https://github.com/DioxusLabs/dioxus.git" }
dioxus-web = { git = "https://github.com/DioxusLabs/dioxus.git" }
dioxus-router = { git = "https://github.com/DioxusLabs/dioxus.git", features = [ "web" ] }
```

**Comment by dxps** [comment]
Right. Initially I was able to just state these in as standard `[dependencies]`.
Now, having:
```toml
[dependencies]

common_model = { path = "../common_model" }

dioxus = "0.3.2"
dioxus-web = { version = "0.3.2" }
dioxus-router = { version = "0.3.0", features = [ "web" ] }
dioxus-use-storage = "0.3.1"

log = "0.4.17"
sir = { version = "0.3.0", features = [ "dioxus" ] }

wasm-logger = "0.2.0"
console_error_panic_hook = "0.1.7"

reqwest = { version="0.11.18", features = [ "blocking", "json" ] }

[patch.crates-io]
dioxus = { git = "https://github.com/DioxusLabs/dioxus.git" }
dioxus-web = { git = "https://github.com/DioxusLabs/dioxus.git" }
dioxus-router = { git = "https://github.com/DioxusLabs/dioxus.git", features = [ "web" ] }
```

and now I get into another interesting issue:
```
[INFO] 👑 Build done.
[WARN] failed to parse `name` custom section Invalid name type (at offset 62727248)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: 

it looks like the Rust project used to create this wasm file was linked against
version of wasm-bindgen that uses a different bindgen format than this binary:

  rust wasm file schema version: 0.2.87
     this binary schema version: 0.2.85

Currently the bindgen format is unstable enough that these two schema versions
must exactly match. You can accomplish this by either updating the wasm-bindgen
dependency or this binary.

You should be able to update the wasm-bindgen dependency with:

    cargo update -p wasm-bindgen

or you can update the binary with

    cargo install -f wasm-bindgen-cli

if this warning fails to go away though and you're not sure what to do feel free
to open an issue at https://github.com/rustwasm/wasm-bindgen/issues!
', src/builder.rs:133:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: 🚫 Serving project failed: Build Failed: Bindgen build failed! 
This is probably due to the Bindgen version, dioxus-cli using `0.2.81` Bindgen crate.
…/frontend on  main [!+] took 41s❯ 
```
