### ISSUE TITLE
App crashes instantly on ios device

### ISSUE THREAD

**Issue by Sha-dos** [DioxusLabs/dioxus#958]
**Problem**

Dioxus app crashes instantly on ios device

**Steps To Reproduce**

- Create simple dioxus app
- Deploy to ios

**Expected behavior**

The app to run properly

**Screenshots**

Cargo.toml
```toml
[package]
name = "todos"
version = "0.1.0"
authors = ["Sha-dos"]
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "todos-desktop"
path = "gen/bin/desktop.rs"

[dependencies]
dioxus = "0.3.2"
#dioxus-desktop = "0.3.0"
dioxus-mobile = "0.3.0"
mobile-entry-point = "0.1.0"
im-rc = "15.0.0"
keyboard-types = "0.6.2"
```

lib.rs
```rust
use dioxus::prelude::*;
use mobile_entry_point::mobile_entry_point;

#[mobile_entry_point]
fn main() {
    dioxus_mobile::launch(app);
}

pub fn app(cx: Scope<()>) -> Element {
    cx.render(rsx!(
        div {
            "Hello from rust!"
        }
    ))
}
```

**Environment:**
 - Dioxus version: [v0.3.2, `master`]
 - Rust version: [v1.67.1, `stable`]
 - OS info: [MacOS]
 - App platform: [`mobile`]

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later
